676201 search data menu list
Pepperi-Addons/basic-logic-blocks pull request #11
Opened 2024-10-18 14:34 UTC by Manish-Josh-pepperi

2024-10-18 16:59 UTC, izhar-ahmad-pepperi requested changes

2024-10-18 16:59 UTC, izhar-ahmad-pepperi commented on client-side/src/app/logic-blocks/search-data/search-data-multiple-resources/search-data-multiple-resources.component.ts
> +          handler: async (selectedData) => {
Try to separate the logic of handler functions, it will enhance the readability of code:

For Example: 

 actions.push({
    title: this.translate.instant("Edit"),
    handler: async (selectedData) => this.handleEdit(selectedRowID),
});

actions.push({
    title: this.translate.instant("Delete"),
    handler: async (selectedData) => this.handleDelete(selectedRowID),
});

2024-10-18 16:59 UTC, izhar-ahmad-pepperi commented on client-side/src/app/logic-blocks/search-data/search-data-multiple-resources/search-data-multiple-resources.component.ts
> +  isEqual(obj1: any, obj2: any): boolean {
Are you still using this function?

2024-10-18 16:59 UTC, izhar-ahmad-pepperi commented on client-side/src/app/logic-blocks/search-data/search-data-multiple-resources/search-data-multiple-resources.component.ts
> +@Component({
Try to structure component as : 

- Class Properties
- Constructor
- Getter/Setters
- Lifecycle Hooks
- Public Methods
- Protected Methods
- Private Methods

2024-10-18 16:59 UTC, izhar-ahmad-pepperi commented on client-side/src/app/services/dialog.service.ts
> +    const dialogConfig = this.dialogService.getDialogConfig({}, sizeType)
We can create a common function and remove code duplicity here, Like: 

`private createDialogConfig(title: string, content: any, buttons: Array<PepDialogActionButton>, sizeType: PepDialogSizeType, actionsType: string = 'custom') { const dialogConfig = this.dialogService.getDialogConfig({}, sizeType); const data = new PepDialogData({ title, actionsType, content, showClose: true, showHeader: true, actionButtons: buttons }); dialogConfig.data = data; return dialogConfig; }`

2024-10-18 16:59 UTC, izhar-ahmad-pepperi commented on client-side/src/app/services/dialog.service.ts
> +  openDialog(title: string, content: ComponentType<any>, buttons: Array<PepDialogActionButton>, input: any, callbackFunc?: (any) => void, sizeType: PepDialogSizeType = 'regular'): void {
Please try to define type for variables instead of using any.

2024-10-18 16:59 UTC, izhar-ahmad-pepperi commented on client-side/src/app/shared/components/base-logic-block.directive/base-logic-block.directive.ts
> +        //
Please remove commented code

2024-10-21 08:40 UTC, Manish-Josh-pepperi commented on client-side/src/app/services/dialog.service.ts
> +  openDialog(title: string, content: ComponentType<any>, buttons: Array<PepDialogActionButton>, input: any, callbackFunc?: (any) => void, sizeType: PepDialogSizeType = 'regular'): void {
As it's a generic function that handles various types of dialog openings. so here we don't have a specific type defined.

2024-10-22 08:56 UTC, izhar-ahmad-pepperi approved these changes

2024-10-27 12:14 UTC, merged