#676202 Search Data logic block cpi changes.
Pepperi-Addons/basic-logic-blocks pull request #14
Opened 2024-10-27 17:51 UTC by Manish-Josh-pepperi

2024-10-29 12:37 UTC, izhar-ahmad-pepperi requested changes

2024-10-29 12:37 UTC, izhar-ahmad-pepperi commented on cpi-side/services/search-data.service.ts
> +    private async getSearchData(configuration: SearchDataConfiguration, context: any): Promise<any> {
Can't we define return type other than any?

2024-10-29 12:37 UTC, izhar-ahmad-pepperi commented on cpi-side/services/search-data.service.ts
> +    private buildQueryString(configuration: SearchDataConfiguration, context: any): any {
please try to define proper types instead of any

2024-11-04 13:11 UTC, roiaharon-pepperi commented on cpi-side/addon-cpi.ts
> +        return res.status(400).json({ error: 'Invalid request body' });
I'm not sure that this is the way to fail the addon api call

2024-11-04 13:16 UTC, roiaharon-pepperi commented on client-side/src/app/logic-blocks/search-data/search-data.component.ts
> +            ResourceParam: {
why have you changed this? what does the 'Dynamic' means in that context?

2024-11-04 13:20 UTC, roiaharon-pepperi commented on cpi-side/services/search-data.service.ts
> +                const documentKey = this.createCompositeDocumentKey(compositeConfiguration);
the function call is redundant.. you already have a separate function to get the documentKey, why using an inner function that simply use join on the array?

2024-11-04 13:23 UTC, roiaharon-pepperi commented on cpi-side/services/search-data.service.ts
> +                const result = await this.getSearchData(config, context);
this is not parallel execution.. the inner await make the call to wait before issuing the next search..

2024-11-04 13:25 UTC, roiaharon-pepperi commented on cpi-side/services/search-data.service.ts
> +        const documentKey = this.getDocumentKey(configuration, context);
this is not the correct logic.. if the configuration is set to get the data by the key, and the key is empty you shouldn't search! but rather throw an exception or return undefined. either way there should be an console.error in here to point out that the configuration is broken

2024-11-04 13:30 UTC, roiaharon-pepperi commented on client-side/src/app/logic-blocks/search-data/search-data.component.ts
> -            this.currentConfiguration.KeyType = DocumentKeyTypes[0];
why are those flags needed? I didn't see where you access them

2024-11-05 01:32 UTC, Manish-Josh-pepperi commented on cpi-side/services/search-data.service.ts
> +                const documentKey = this.createCompositeDocumentKey(compositeConfiguration);
As per the last comment from Teammates, we should divide our code into smaller functions for better readability and understanding. Because of that, I have written that separate function outside of it.

2024-11-05 01:33 UTC, Manish-Josh-pepperi commented on client-side/src/app/logic-blocks/search-data/search-data.component.ts
> -            this.currentConfiguration.KeyType = DocumentKeyTypes[0];
I am using them in the HTML template file _**client-side/src/app/logic-blocks/search-data/search-data.component.html**_

`<div *ngIf="isUDCKeyByFields">
            <ng-container *ngFor="let field of documentKeyFields">
                <pep-select class="max-width"
                    [options]="fieldOptionsMap[field]"
                    [mandatory]="true"
                    [label]="field | translate"
                    [value]="currentConfiguration?.KeyFields[field]"
                    (valueChange)="onKeyFieldChange($event, field)">
                </pep-select>
                <div class="pep-border-bottom"></div>
            </ng-container>
        </div>`
        
        `<!-- Autogenerated Key -->
        <div *ngIf="isUDCKeyAutoGenerated">
            <pep-select class="max-width" [options]="flowStringTypeParams" [mandatory]="true" [label]="'Key' | translate"
                [value]="currentConfiguration?.ResourceParam.Value" (valueChange)="onKeyStringFlowParamChange($event)">
            </pep-select>
            <div class="pep-border-bottom"></div>
        </div>`

2024-11-05 01:35 UTC, Manish-Josh-pepperi commented on client-side/src/app/logic-blocks/search-data/search-data.component.ts
> +            ResourceParam: {
Here we added this b'z getParamValue() method required this as a mandatory first parameter.
The code FlowParamSource will be updated based on the type selected on the UI.

In our last call discussion, we decided to get the value from the getParamValue() function from the context object. Because of that, I changed this here.

2024-11-05 02:26 UTC, Manish-Josh-pepperi commented on cpi-side/services/search-data.service.ts
> +        const documentKey = this.getDocumentKey(configuration, context);
Yes, I think I am handling it in the same way. 
` const documentKey = this.getDocumentKey(configuration, context);
if(documentKey){
// then go for getBykey search
}
else we are going for where clause search.
`

let me know if I still need to make any changes here.

2024-11-07 10:00 UTC, roiaharon-pepperi requested changes

2024-11-07 12:09 UTC, Manish-Josh-pepperi commented on client-side/src/app/logic-blocks/search-data/search-data.component.ts
> +        this.isFieldEnabled = this.documentKeyFields.map((_, index) => index === 0);
Reason is 
suppose we have a composite key resource with the following fields
[fidle1, field2, field3]

Here, we want to make sure the user selects the fields in sequence instead of selecting the random key from the list. if we allow the user to select any field, then there is a chance our composite keys sequence will lost. 

so at the initial point, we are enabling the field1 dropdown. Once the user selects a value, it will enable a second dropdown, and so on.

2024-11-07 12:34 UTC, Manish-Josh-pepperi commented on cpi-side/services/search-data.service.ts
> +        if (configuration.KeyType === "AutoGenerate" && configuration.KeyFields && configuration.KeyFields.length) {
Got it, let me refactor this getDocumentKey(-,-) function. But I think Keyfields should be checked inside this function only. "**Ensure getDocumentKey is robust and capable of handling the invalid or missing Keyfields input without reliance on the caller**"

2024-11-07 16:35 UTC, Manish-Josh-pepperi commented on cpi-side/services/search-data.service.ts
> +        const documentKey = this.getDocumentKey(configuration, context);
It was handled differently. On Ui, if the user changes the Search type by multiple and adds the Source query, we are resetting the KeyFields. [Here is the code](https://github.com/Pepperi-Addons/basic-logic-blocks/pull/14/files#diff-f287809f47b6c29ea689956372755a8c01b3ade7c126c5fadfab78dfe3aeb9d7R218)

So, at a time, it will only get one query, either By single key or by multiple resources by query.

2024-11-10 05:13 UTC, roiaharon-pepperi approved these changes

2024-11-10 05:13 UTC, roiaharon-pepperi commented on cpi-side/services/search-data.service.ts
> +        configurations.forEach((config, index) => {
why looping the configuration again? why not using the "then" method on the promise?
you can do something similar to this:
configurations.map((config) => this.getSearchData(config, context).then((result) => {{add logic here}}) );

2024-11-10 08:46 UTC, roiaharon-pepperi commented on client-side/src/app/logic-blocks/search-data/search-data.component.ts
> +        this.isFieldEnabled = this.documentKeyFields.map((_, index) => index === 0);
but you have the index from the for loop in the HTML.. you can use that in order to know which index of the array to set.. right now you still have this issue, because i can always go back to the previous field and update it again (or at least I should have the option to do so)

2024-11-10 08:48 UTC, roiaharon-pepperi commented on cpi-side/services/search-data.service.ts
> +        if (configuration.KeyType === "AutoGenerate" && configuration.KeyFields && configuration.KeyFields.length) {
if getDocumentKey function is private, and always called from the same function, I'm not seeing any difference in you're approach. but I'm open to your solution as long as you will check it only once

2024-11-11 04:58 UTC, izhar-ahmad-pepperi approved these changes

2024-11-11 05:11 UTC, merged