#676537 setfield value list implementation
Pepperi-Addons/basic-logic-blocks pull request #15
Opened 2024-10-30 11:10 UTC by Manish-Josh-pepperi

2024-11-08 12:22 UTC, izhar-ahmad-pepperi requested changes

2024-11-08 12:22 UTC, izhar-ahmad-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
> +    //   this.translate.instant("SEARCH_DATA.TITLE"),
Remove Commented code, multiple places

2024-11-08 12:22 UTC, izhar-ahmad-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
> +    const indexToRemove = this._currentConfiguration.findIndex(item => item.Resource === selectedRowID);
Is Resource unique for each item?

2024-11-08 12:22 UTC, izhar-ahmad-pepperi commented on shared/build/shared/index.js
> +__exportStar(require("./set-field-value.model"), exports);
Why are there changes from build?

2024-11-10 05:18 UTC, Manish-Josh-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
> +    //   this.translate.instant("SEARCH_DATA.TITLE"),
These are going to be used in the next PR. I have enabled these lines of code.
in another PR.

2024-11-10 05:21 UTC, roiaharon-pepperi requested changes

2024-11-10 05:21 UTC, roiaharon-pepperi commented on shared/build/shared/index.d.ts
build folder shouldn't be commited.. please add this folder to the git.ignore file

2024-11-10 05:21 UTC, roiaharon-pepperi commented on shared/set-field-value.model.ts
> +export interface SetFieldValueConfiguration {
isn't this interface is for the searchData? where is the path parameters? and other configuration?

2024-11-10 05:21 UTC, roiaharon-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
> +    const indexToRemove = this._currentConfiguration.findIndex(item => item.Resource === selectedRowID);
I'm not sure what exactly are you doing here.. didn't you generated a uuid for each line? why not using it?
resource is not unique here (maybe {{resource}}_{{fieldName}}

2024-11-12 03:30 UTC, Manish-Josh-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
> +    const indexToRemove = this._currentConfiguration.findIndex(item => item.Resource === selectedRowID);
Yes, that has been taken care of in the next task PR.

2024-11-12 03:34 UTC, Manish-Josh-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
> +    const filteredConfig = this._currentConfiguration.filter(config => config.Resource !== "");
this has been taken care of in the next PR.

2024-11-12 13:26 UTC, roiaharon-pepperi requested changes

2024-11-12 13:26 UTC, roiaharon-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.scss
> +  min-height: 32rem;
I have a deja voo, why is this style here? isn't this a dialog?

2024-11-12 13:26 UTC, roiaharon-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
> +    debugger;
remove debugger

2024-11-12 13:26 UTC, roiaharon-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
> +    filteredConfig.forEach(config => this.resourceSet.add(config.Source));
you are already looping through all the items with the filter, why not do this in the same callback?

2024-11-12 13:26 UTC, roiaharon-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
>        this.hostObject.Configuration = this._currentConfiguration;
why are you setting the host object? this should be read only. if you want to update the configurations there are output callbacks to achieve that

2024-11-12 13:26 UTC, roiaharon-pepperi commented on .gitignore
> +shared/build
this still not working.. there are still build files in the commit..
this is the git.ignore from other project, maybe try to use that
publish
var_sk
\*\*/node_modules/\*\*
\*\*/build/\*\*

2024-11-12 13:40 UTC, Manish-Josh-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
> +    filteredConfig.forEach(config => this.resourceSet.add(config.Source));
all this taken care in next PR #16

2024-11-12 14:39 UTC, roiaharon-pepperi approved these changes

2024-11-12 14:39 UTC, merged