676538 add edit setfield value
Pepperi-Addons/basic-logic-blocks pull request #16
Opened 2024-11-06 12:04 UTC by Manish-Josh-pepperi

2024-11-10 08:17 UTC, roiaharon-pepperi requested changes

2024-11-10 08:17 UTC, roiaharon-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
> +    if (data && !this.resourceSet.has(data.UIListUUID)) {
why do you need the resourceSet? why not add the "key" to the configuration object itself.. also, didn't we say you will generate a uuid?

2024-11-10 08:17 UTC, roiaharon-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.ts
> +    this.hostObject.Configuration = this._currentConfiguration;
why do you need the current configuration on the "Add" dialog?

2024-11-10 08:17 UTC, roiaharon-pepperi commented on shared/set-field-value.model.ts
> +  UIListUUID?: string
this is not a good property name.. this should be Key.

2024-11-10 08:17 UTC, roiaharon-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.service.ts
> +    this.getPapiCall(`/meta_data/${type}/fields`).subscribe((fields) => {
this call should be on the server side, not the client side.. there shouldn't be any external call other that your server side

2024-11-10 08:17 UTC, roiaharon-pepperi commented on server-side/services/utilities-service.ts
what is this file? why do you need it?

2024-11-10 08:17 UTC, roiaharon-pepperi commented on server-side/services/transactions-service.ts
what is this file? why do you need it?

2024-11-10 08:17 UTC, roiaharon-pepperi commented on server-side/api.ts
> +    const service = new TransactionsService(client, ''); // check if we can get the atdUUID from UI, for now we dont have one
you don't have an AtdUUID because you're not in the context of ATD..

2024-11-12 04:03 UTC, Manish-Josh-pepperi commented on client-side/src/app/logic-blocks/set-field-value/set-field-value.component.scss
> +.configuration-content {
No, we need this as the dialog size is not enough for the initial box.

2024-11-13 05:31 UTC, Manish-Josh-pepperi commented
Closing this Pr as it contains unrequired commits.

2024-11-13 05:31 UTC, closed without merging