#677471-Added CPI Side logic
Pepperi-Addons/basic-logic-blocks pull request #21
Opened 2024-11-21 10:50 UTC by siva-pepperi

2024-11-22 07:10 UTC, izhar-ahmad-pepperi requested changes

2024-11-22 07:10 UTC, izhar-ahmad-pepperi commented on cpi-side/services/set-field-value.service.ts
> +  private async setResourceFields(config: SetFieldValueConfiguration, context: any): Promise<void> {
use IContext instead of any.
import { IContext } from "@pepperi-addons/cpi-node/build/cpi-side/events";

2024-11-22 07:10 UTC, izhar-ahmad-pepperi commented on cpi-side/services/set-field-value.service.ts
> +    let sourceValue: string;
we can use ternary operator, that will make code shorter and easier to read.
let sourceValue = (Source === 'Static') ? SourceField : context?.[SourceField];

2024-11-22 07:10 UTC, izhar-ahmad-pepperi commented on cpi-side/services/set-field-value.service.ts
> +      [DestinationField]: sourceValue || DefaultValue
The nullish operator (??) is used instead of the logical OR (||). This ensures that only null or undefined values for sourceValue are replaced by DefaultValue. The ?? operator will not overwrite sourceValue if it's something like 0 or false.

2024-11-25 07:12 UTC, roiaharon-pepperi requested changes

2024-11-25 07:12 UTC, roiaharon-pepperi commented on cpi-side/addon-cpi.ts
> +    res.json(await service.setFieldValueInResource(req.body, req.context));
you should add try...catch, if the function will crash, you will crash the entire app. please look at other cpi methods implementation for example

2024-11-25 07:12 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +  private async setResourceFields(config: SetFieldValueConfiguration, context: any): Promise<void> {
no.. importing directly from the build folder is never a good idea.. if it's not exported, that this shouldn't be used

2024-11-25 07:12 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +      sourceValue = sourceValue[FieldParamType === "Static" ? Field : context?.[Field]];
I think you have a redundant dot.. 
context?[field] and not context?**.**[field]

2024-11-25 07:12 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +    await pepperi.resources.resource(DestinationObject).post({
this is not the way to update a transaction.. this will not work.. how did you test it?

2024-11-25 07:22 UTC, siva-pepperi commented on cpi-side/services/set-field-value.service.ts
> +      sourceValue = sourceValue[FieldParamType === "Static" ? Field : context?.[Field]];
? will not work it should be ?. @roiaharon-pepperi 
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/34c6d243-5c79-479d-9ae4-918aba1ac430">

2024-11-25 07:22 UTC, siva-pepperi commented on cpi-side/addon-cpi.ts
> +    res.json(await service.setFieldValueInResource(req.body, req.context));
Will add the checks

2024-11-25 10:49 UTC, siva-pepperi commented on cpi-side/services/set-field-value.service.ts
> +    await pepperi.resources.resource(DestinationObject).post({
Yep, i missed it, I have fixed it

2024-11-25 11:01 UTC, roiaharon-pepperi requested changes

2024-11-25 11:01 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +		return resource[DestinationObject].update({
you're not handling transaction lines as you should.. when updating transaction lines, the uuid will be the destinationUUID will be of the transaction, and not line. you should loop through all the lines of the transaction, and get the correct value from the corresponding item on the UDC (in that case sourceValue should be an array of objects).

2024-11-26 14:11 UTC, roiaharon-pepperi requested changes

2024-11-26 14:11 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +    const modifiedObjects = lines.objects.map((lineItem) => ({...lineItem, [updateParam]: updateValue }))
this still doesn't implement the logic we talked about Yesterday..

2024-12-01 13:27 UTC, roiaharon-pepperi approved these changes

2024-12-01 13:27 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +	// eslint-disable-next-line max-lines-per-function
please remove this comment and break the function to withstand the lint limitation

2024-12-01 13:27 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +		const modifiedObjects = lines?.objects?.map((lineItem) => ({ ...lineItem, [updateParam]: updateValue }));
this will still won't work.. you need to go over all the items and match the items uuid's.. remove the filter from the search of the transaction lines.. and for each line, you need to get the item from the the updateValue in which the itemUUID is the same as the itemUUID from the line, and the get the value from the given field

2024-12-02 10:55 UTC, roiaharon-pepperi requested changes

2024-12-02 10:55 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +		const resource = await pepperi.papiClient.userDefinedCollections.schemes.name(Resource).get();
you should check with resources.resource('resources') as the resource can be other than UDC

2024-12-02 10:55 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +		return Data?.map((value) => value[ItemIdField]).flat();
why do you need only the UUID's? will also need to value of the requested field

2024-12-02 14:03 UTC, roiaharon-pepperi requested changes

2024-12-02 14:03 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +	private async updateTransactions(UUID, updateParam, updateValue, fieldConfig: SetFieldValueConfiguration["SourceFieldPath"]): Promise<any> {
this is exactly the same logic as in the updateActivites apart from the api used. please merge those 2 functions with the api as a parameters.. another option would be construct the object array here, and update the api on the caller function

2024-12-02 18:45 UTC, roiaharon-pepperi requested changes

2024-12-02 18:45 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +			return await resource[DestinationObject](context[DestinationUUID], DestinationField, sourceValue ?? DefaultValue, SourceFieldPath, DestinationObject);
why do you need the await in here?

2024-12-02 18:45 UTC, roiaharon-pepperi commented on cpi-side/services/set-field-value.service.ts
> +			for ( const object of allUpdateObjects) {
why did you add this? why not update the object inside the setResourceFields?

2024-12-03 14:21 UTC, roiaharon-pepperi approved these changes

2024-12-03 14:21 UTC, merged